baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "chiihou"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[taxonomies]
  category = "blog/categories"
  tag = "blog/tags"

#[[menu.main]]
[[menu.feed]]
name = "blog"
url = "/blog/"
weight = 1
[[menu.feed]]
name = "projects"
url = "/projects/"
weight = 2


[params]
custom_css = ["/css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = "built with [hugo](https://gohugo.io/) | themed [hugo-classic](https://github.com/goodroot/hugo-classic) by goodroot | cheily 2024"

[permalinks]
post = "/blog/post/:slug/"
[permalinks.term]
category = "/blog/categories/:slug/"
tag = "/blog/tags/:slug/"